- name: This playbook will demonstrate installing,configuring and deploying web pages to nginx web server
  hosts: all
  gather_facts: False 
  vars:
     - automation_tool: Ansible
     - provisioner_tool: Docker
#    - proxy_conf:
#         http_proxy: "http://genproxy.amdocs.com:8080"
#         https_proxy: "https://genproxy.amdocs.com:8080"
#         HTTP_PROXY: "http://genproxy.amdocs.com:8080"
#         HTTPS_PROXY: "https://genproxy.amdocs.com:8080"
  tasks:
    - name: Install nginx web server
      apt: name=nginx state=latest update_cache=yes
#      environment: "{{proxy_conf}}"
#
    - name: Create the nginx web root folder 
      shell: mkdir -p /var/html

    - name: Configure nginx web root folder
      copy: src=default dest=/etc/nginx/sites-available/default
  
    - name: Start the nginx service
      shell: service nginx restart

    - name: Deploy html page into nginx server
      template: src=index.html.j2 dest=/var/html/index.html
