kubectl apply -f app-deployment.yaml
kubectl apply -f app-service.yaml
kubectl apply -f default-backend-deployment.yaml
kubectl apply -f default-backend-service.yaml
kubectl apply -f nginx-ingress.yaml
kubectl apply -f nginx-ingress-controller-config-map.yaml
kubectl apply -f nginx-ingress-controller-roles.yaml
kubectl apply -f nginx-ingress-controller-deployment.yaml
kubectl apply -f nginx-ingress-controller-service.yaml
kubectl apply -f app-ingress.yaml
