apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: "nginx"
    ver: "2.0"
  name: nginx
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "nginx"
      ver: "1.0"
  strategy:
    rollingUpdate:
      maxSurge: 1 
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: "nginx"
        ver: "1.0"
      name: nginx
    spec:
      containers:
      - image: nginx:1.14
        imagePullPolicy: Always
        name: nginx-container
        ports:
        - containerPort: 80
          protocol: TCP
