apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
     app: "nginx"
     ver: "1.0"
spec:
  containers:
     - name: nginx-container
       image: nginx
       ports:
         - containerPort: 80
           protocol: TCP
